// <auto-generated />
using System;
using Disval.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Disval.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Disval.Entidades.CCV", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Comprobante")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDeEmision")
                        .HasColumnType("datetime(6)");
                                        

                    b.Property<int>("PuntoDeVenta")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("CCVs");
                });

            modelBuilder.Entity("Disval.Entidades.DCV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CodigoLaboratorio")
                        .HasColumnType("int");

                    b.Property<int>("IDCCV")
                        .HasColumnType("int");

                    b.Property<int>("transaccionCCVID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("transaccionCCVID");

                    b.ToTable("DCVs");
                });

            modelBuilder.Entity("Disval.Entidades.TFC", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("codigoLaboratorio")
                        .HasColumnType("int");

                    b.Property<double>("numeroDeDocumento")
                        .HasColumnType("double");

                    b.Property<int>("serie")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("TFCs");
                });

            modelBuilder.Entity("Disval.Entidades.DCV", b =>
                {
                    b.HasOne("Disval.Entidades.CCV", "transaccionCCV")
                        .WithMany()
                        .HasForeignKey("transaccionCCVID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("transaccionCCV");
                });
#pragma warning restore 612, 618
        }
    }
}
